version: "3.9"
services:
  nextjs:
    image: metaphor1990/z11g:latest
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ~/workspace/app_data:/app/app_data
  nginx:
    image: metaphor1990/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/workspace/nginx:/etc/nginx/conf.d
    restart: always
