name: Package and Release

on:
  push:
    branches:
      - master

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate tag name
        id: tag-name
        run: echo "::set-output name=tag_name::v$(date +'%Y%m%d-%H%M%S')"

      - name: Create ZIP file
        run: |
          zip -r website.zip ./src/*
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag-name.outputs.tag_name }}
          release_name: ${{ steps.tag-name.outputs.tag_name }}
          body: |
            Release website.
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: website.zip

      - name: Upload asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: website.zip
          asset_name: website.zip
          asset_content_type: application/zip
